import type { Metadata } from "next";
import { Gothic_A1 } from "next/font/google";
import "./globals.css";

const gothic = Gothic_A1({
    weight: "400",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            {/* side nav 넣고 one page scroll 사용 */}
            <body className={gothic.className}>
                {/* side nav  / layout 말고 page 쪽으로 */}
                {children}
            </body>
        </html>
    );
}
